### ISSUE TITLE
Allow editing BNN supplier without entering password

### ISSUE THREAD

**Issue by wvengen** [foodcoops/sharedlists#9]
When editing a supplier with BNN synchronization enabled, a password is required.
Let's keep the current password when it is empty in the form.

**Comment by JuliusR** [comment]
Can not reproduce this right now. I guess it was fixed by 397d63380f3f2788124050a03d2852e431c24947 (see https://github.com/foodcoops/sharedlists/commit/397d63380f3f2788124050a03d2852e431c24947#diff-cd398da04abc8473e3820671850971bdR64).
